language: python
python:
  - "3.6"
  - "3.7-dev"
  - "3.8"
  - "3.9"
  
env:
  - DJANGO_VERSION=3.2.7
  
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
  
script: python foundup/manage.py test
after_success:
  â€” coveralls